spring.application.name=falcon

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.api-key=${OPENROUTER_API_KEY}
spring.ai.openai.chat.options.model=openai/gpt-4o
spring.ai.openai.chat.options.temperature=0.2
spring.ai.openai.chat.options.response-format.type=json_object
